### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'finish'

### ISSUE THREAD

**Issue by Zardoz89** [philleonard/maven-progress-bar#2]
```
mvn clean | mvnp
Traceback (most recent call last):
  File "/usr/local/bin/mvnp", line 126, in <module>
    match()
  File "/usr/local/bin/mvnp", line 109, in match
    bar.finish()
AttributeError: 'NoneType' object has no attribute 'finish'

```

```
 mvn clean package | mvnp
Traceback (most recent call last):
  File "/usr/local/bin/mvnp", line 126, in <module>
    match()
  File "/usr/local/bin/mvnp", line 109, in match
    bar.finish()
AttributeError: 'NoneType' object has no attribute 'finish'

```

Also, takes a lot of time showning nothing

kUbuntu 17.10 with kernel 4.15.18-041518-generic x86_64

Python 3.6.3 (default, Oct  3 2017, 21:45:48) 
[GCC 7.2.0] on linux

**Comment by philleonard** [comment]
What version of `progressbar2` did pip install? 

```bash
$ pip3 show progressbar2
```

**Comment by Zardoz89** [comment]
```
> pip3 show progressbar2
Name: progressbar2
Version: 3.38.0
Summary: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
Home-page: https://github.com/WoLpH/python-progressbar
Author: Rick van Hattem (Wolph)
Author-email: wolph@wol.ph
License: BSD
Location: /home/luis/.local/lib/python3.6/site-packages
Requires: python-utils, six

```

**Comment by jianbinw** [comment]
> ```
> > pip3 show progressbar2
> Name: progressbar2
> Version: 3.38.0
> Summary: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
> Home-page: https://github.com/WoLpH/python-progressbar
> Author: Rick van Hattem (Wolph)
> Author-email: wolph@wol.ph
> License: BSD
> Location: /home/luis/.local/lib/python3.6/site-packages
> Requires: python-utils, six
> ```

This problem is probably caused by the version of Maven is old and the output of building info doesn't contain the progress information ( like "[2/10]" ). Please try to upgrade Maven to later version (> 3.5.3, refer to https://maven.apache.org/docs/3.5.3/release-notes.html).

**Comment by Zardoz89** [comment]
I don't know what exact version I had then. Probably was the latest 3.3.x . I have now 3.6.1 and works fine.

**Comment by philleonard** [comment]
Thanks for following this up!
